// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace MyPayroll
{
    public partial class EmployeeBankDetails
    {
        public int Id { get; set; }
        public int EmployeeId { get; set; }
        public int BankId { get; set; }
        public int BranchId { get; set; }
        public string AccountNumber { get; set; }
        public string AccountName { get; set; }
        public int StatusId { get; set; }
        
        public int IsDefaultBank { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? DateCreated { get; set; }
    }
}